### ISSUE TITLE
TestSubscriber constructor with delegate Subscriber

### ISSUE THREAD

**Issue by sdeleuze** [reactor/reactive-streams-commons#3]
In Reactor I have created a [`TestSubscriber`](https://github.com/reactor/reactor-core/blob/master/src/main/java/reactor/core/test/TestSubscriber.java) inspired from the one of RSC, and I have a question.

I am not sure if we want (on Reactor side) to keep constructors using a delegate `Subscriber` because I am not sure about the use cases, could you please give me some hints about what use cases they fit in?

Thanks in advance for your help.

**Comment by akarnokd** [comment]
It is a remnant of RxJava's `TestSubscriber`. Some people like to verify event ordering via Mockito  yet they need `await()` to make sure the source completes. This constructor allows you to forward events to this mock. I personally don't use Mockito anymore as the `assertX` of the `TestSubscriber` is quite enough for the Rsc's unit tests.

**Comment by sdeleuze** [comment]
Ok thanks!
