### ISSUE TITLE
Clarification on the Scheduler.Worker.schedule contract

### ISSUE THREAD

**Issue by agentgt** [reactor/reactive-streams-commons#30]
The `Scheduler.Worker#schedule` javadoc says:

```java

    /**
     * Creates a worker of this Scheduler that executed task in a strict
     * FIFO order, guaranteed non-concurrently with each other.
     * <p>
     * Once the Worker is no longer in use, one should call shutdown() on it to
     * release any resources the particular Scheduler may have used.
     * 
     * <p>Tasks scheduled with this worker run in FIFO order and strictly non-concurrently, but
     * there are no ordering guarantees between different Workers created from the same
     * Scheduler.
     * 
     * @return the Worker instance.
     */
```

The FIFO order seems to be preserved in all of the code examples but I don't understand the semantics being used for "*strictly non-concurrently*".

For example it appears ExecutorServiceScheduler will have Workers that will run tasks concurrently unless a single thread executor is used.

In other Reactive Streams implementations that have a scheduler aka rxjava there is no mention of that guarantee.

Is there some implementation logic I'm missing or am I misunderstanding the doc?

**Comment by akarnokd** [comment]
Please read the [Scheduler](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Scheduler.html) JavaDocs.

> The so-called Scheduler.Workers of a Scheduler can be created via the createWorker() method which allow the scheduling of multiple Runnable tasks in an isolated manner. **Runnable tasks scheduled on a Worker are guaranteed to be executed sequentially and in a non-overlapping fashion. Non-delayed Runnable tasks are guaranteed to execute in a First-In-First-Out order but their execution may be interleaved with delayed tasks.** In addition, outstanding or running tasks can be cancelled together via Disposable.dispose() without affecting any other Worker instances of the same Scheduler.

**Comment by agentgt** [comment]
Yes but that is the RxJava documentation of which I'm familiar with and is far more clear. I just thought it might be worthwhile to put something similar in this project.

**Comment by akarnokd** [comment]
This project is no longer developed and we applied the knowledge and further clarifications in the respective libraries long ago.
