### ISSUE TITLE
Naming?

### ISSUE THREAD

**Issue by viktorklang** [reactor/reactive-streams-commons#4]
Hi,

I only skimmed the README, but shouldn't the Transformations be named "Processor" rather than "Publisher"? (https://github.com/reactor/reactive-streams-commons#supported-transformations)

**Comment by akarnokd** [comment]
Processors implement `Subscriber` and are 1 to X in general. Our transformations are wrappers that allow N to X in general and don't have a `Subscriber` front, and they shouldn't have. This is the basis of a reusable fluent API unlike Java Streams.

**Comment by viktorklang** [comment]
Ah, ok, thanks for elaborating, @akarnokd!
