### ISSUE TITLE
Throttling on leading and trailing edge

### ISSUE THREAD

**Issue by bripkens** [reactor/reactive-streams-commons#6]
## Request
It would be great when Reactor would support throttling on leading and trailing edge. This is quite a common use case when working on applications that provide data to some kind of reactive user interface, but may be an interesting feature in general.

*Disclaimer: This ticket describes throttling requirements from the perspective of a UI. Various kinds of consumers may have the same requirements, even though they are not explicitly mentioned.*

## What does this mean?
The popular JS library lodash implements this throttling behavior as a default (as mentioned before, quite a common use case for UI applications). Instead of trying to explain this with words, please check out the following JS Bin which shows the behavior in action:

 - **JS Bin**: http://jsbin.com/modenetujo/edit?js,console
 - **lodash throttling documentation**: https://lodash.com/docs#throttle

For easier reference, here the example logic and resulting output:

```javascript
const windowSize = 100;
const fn = _.throttle(v => console.log(v), windowSize);

fn('a');                                     // start of first window
setTimeout(() => fn('b'), windowSize * 0.5); // in first window, but dropped due to successive message
setTimeout(() => fn('c'), windowSize * 0.9); // last message in first window

setTimeout(() => fn('d'), windowSize * 1.2); // first message in new window


// expected output:
// a
// c
// d
```

## Why is this interesting?
In reactive UIs, throttling logic which emits only on a single edge, i.e. either leading or trailing edge, is insufficient as:

 - The UI should not have to wait for the end of a time window to receive a value when there is only a single value (read: trailing edge only throttling).
 - Only emitting on the leading edge is insufficient as this can result in permanent inconsistent data (read: leading edge only throttling).

**Comment by ifesdjeen** [comment]
+1

**Comment by akarnokd** [comment]
Rsc has three operators that can support such UI behavior already:

  - PublisherSample: take the last value whenever the sampler fires
  - PublisherThrottleFirst: take the first value and then noting until the other fires
  - PublisherThrottleTimeout: emit the last value only if no other values appear until the other fires

Maybe these are not exposed or named differently in reactor-core/stream.

**Comment by bripkens** [comment]
@akarnokd: I not sure I understand how these could be defined in order to achieve this behavior. Simply chaining `throttleFirst` and `throttleLast` would not result in the desired behavior.

**Comment by smaldini** [comment]
Documentation with marble coming but I was also trying to understand precisely what's wrong with 
http://projectreactor.io/stream/docs/api/reactor/rx/Stream.html#throttleFirst-reactor.fn.Function-
http://projectreactor.io/stream/docs/api/reactor/rx/Stream.html#throttleTimeout-reactor.fn.Function-

**Comment by smaldini** [comment]
I think I get it, please confirm :dancer: 
You want to emit the first And last value of a given window ? But if window is exact (e.g. exact-time, exact-size). E.g. sampleStartStop.

**Comment by ifesdjeen** [comment]
I'll try to explain the way I have understood: 
  * emit at most once per time period
  * if there was an emit within the time period, wait until the end of peiord 
  * if there was no emit within the time period, emit immediately 

:)

**Comment by smaldini** [comment]
Ok makes sense, now so 
A [--B [-----] ---] C [-------] D

**Comment by bripkens** [comment]
Not exactly. I'd recommend inspecting the JSBin referenced above and playing with the test. I can try to explain it in words, but that might not be as accurate :)

 - emit at most *twice* per time period
 - if there was no emit, emit nothing (read: no polling)
 - if there was one emit, emit immediately and note the start of a new time period
 - if there is more than one emit within a time period, emit at the end of the time period (i.e. emit at most at start and end of a time period).

**Comment by ifesdjeen** [comment]
Ok, I'd say just suggest to submit a PR for exactly what you want :) you understand the problem better than all of us anyways :))

**Comment by smaldini** [comment]
If you can hand draw or similar, I suggest a marble diagram like 
![](https://raw.githubusercontent.com/reactor/projectreactor.io/master/src/main/static/assets/img/marble/workqueue.png)

**Comment by ifesdjeen** [comment]
I guess that one is not relevant anymore.
